package filebox;


/**
* filebox/fileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 03 April 2013 20:38:14 o'clock IST
*/

public interface fileOperations 
{
  int id ();
  String name ();
  void name (String newName);
  String content ();
  void content (String newContent);
  int status ();
  void status (int newStatus);

  // 0 - private, 1 - public
  int userid ();

  // 0 - private, 1 - public
  void userid (int newUserid);
  org.omg.CORBA.Any contentbinary ();
  void contentbinary (org.omg.CORBA.Any newContentbinary);
} // interface fileOperations
