package filebox;


/**
* filebox/fileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Tuesday, April 2, 2013 6:42:25 PM BST
*/

public interface fileOperations 
{
  int id ();
  String name ();
  void name (String newName);
  String content ();
  void content (String newContent);
  int status ();
  void status (int newStatus);

  // 0 - private, 1 - public
  int userid ();

  // 0 - private, 1 - public
  void userid (int newUserid);
} // interface fileOperations
