package filebox;


/**
* filebox/listenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Tuesday, April 2, 2013 6:42:25 PM BST
*/

public interface listenerOperations 
{
  void message (String message);
} // interface listenerOperations
