package filebox;


/**
* filebox/MessageServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 03 April 2013 20:38:14 o'clock IST
*/

public interface MessageServerOperations 
{
  void register (filebox.listener lt);
} // interface MessageServerOperations
