package filebox;


/**
* filebox/serviceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Tuesday, April 2, 2013 6:42:25 PM BST
*/

public interface serviceOperations 
{
  int addUser (String username, String password);
  filebox.user getUser (int id);
  int login (String username, String password);
  int addFile (String name, String content, int status, int userid);
  filebox.file getFile (String filename, int uid);
  filebox.file[] getFiles (int userid);
  filebox.file changeFileStatus (String filelist, short fileid, short filestatus);
  filebox.file fileUpdate (String filelist, int lastchanged, short fileid, filebox.listener callback);
  void removeFile (short fileid);
  void register (filebox.listener lt);
  filebox.status getStatus ();
} // interface serviceOperations
