package filebox;

/**
* filebox/serviceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 03 April 2013 20:38:14 o'clock IST
*/

public final class serviceHolder implements org.omg.CORBA.portable.Streamable
{
  public filebox.service value = null;

  public serviceHolder ()
  {
  }

  public serviceHolder (filebox.service initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = filebox.serviceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    filebox.serviceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return filebox.serviceHelper.type ();
  }

}
