package filebox;


/**
* filebox/serviceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 03 April 2013 20:38:14 o'clock IST
*/

public interface serviceOperations 
{
  int addUser (String username, String password);
  filebox.user getUser (int id);
  int login (String username, String password);
  int addFile (String name, String content, int status, int userid);
  filebox.file getFile (String filename, int uid);
  filebox.file changeFileStatus (String filelist, short fileid, short filestatus);
  filebox.file fileUpdate (String filelist, int lastchanged, short fileid, filebox.listener callback);
  filebox.file[] getFiles (int uid, String content, String filename);
  void removeFile (short fileid);
  void register (filebox.listener lt);
  filebox.status getStatus ();
  filebox.file addFileBinary (org.omg.CORBA.Any contentbinary, String filename, short fileid, short filestatus);
} // interface serviceOperations
