package filebox;

/**
* filebox/statusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Tuesday, April 2, 2013 6:42:25 PM BST
*/

public final class statusHolder implements org.omg.CORBA.portable.Streamable
{
  public filebox.status value = null;

  public statusHolder ()
  {
  }

  public statusHolder (filebox.status initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = filebox.statusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    filebox.statusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return filebox.statusHelper.type ();
  }

}
