package filebox;


/**
* filebox/statusOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 03 April 2013 20:38:14 o'clock IST
*/

public interface statusOperations 
{
  int code ();
  void code (int newCode);

  // 0 - success, 1 - error
  String text ();

  // 0 - success, 1 - error
  void text (String newText);
} // interface statusOperations
