package filebox;


/**
* filebox/userPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 03 April 2013 20:38:14 o'clock IST
*/

public class userPOATie extends userPOA
{

  // Constructors

  public userPOATie ( filebox.userOperations delegate ) {
      this._impl = delegate;
  }
  public userPOATie ( filebox.userOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public filebox.userOperations _delegate() {
      return this._impl;
  }
  public void _delegate (filebox.userOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int id ()
  {
    return _impl.id();
  } // id

  public String username ()
  {
    return _impl.username();
  } // username
  public void username (String newUsername)
  {
    _impl.username(newUsername);
  } // username

  public String password ()
  {
    return _impl.password();
  } // password
  public void password (String newPassword)
  {
    _impl.password(newPassword);
  } // password

  public int lastlogin ()
  {
    return _impl.lastlogin();
  } // lastlogin
  public void lastlogin (int newLastlogin)
  {
    _impl.lastlogin(newLastlogin);
  } // lastlogin

  private filebox.userOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class userPOATie
