package filebox;

/**
* filebox/userHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Tuesday, April 2, 2013 6:42:25 PM BST
*/

public final class userHolder implements org.omg.CORBA.portable.Streamable
{
  public filebox.user value = null;

  public userHolder ()
  {
  }

  public userHolder (filebox.user initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = filebox.userHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    filebox.userHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return filebox.userHelper.type ();
  }

}
